# Generated by Django 6.0.1 on 2026-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_categorymenu_subcategory_foodmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
